hello:build:
    stage: build
    script:
        - make -C lab6/hello clean all
    only:
        - master

hello:test:
    stage: test
    script:
        - Make -C hello clean tests
    only:
        - master